apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployement
spec:
  selector:
    matchLabels:
      app: redis-deployement
  replicas: 1
  template:
    metadata:
      name: redis-deployement
      labels:
        app: redis-deployement
    spec:
      containers:
        - image: redis:alpine
          name: redis-container
