apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployement
spec:
  selector:
    matchLabels:
      app: vote-pods
  replicas: 3
  template:
    metadata:
      name: vote-pods-template
      labels:
        app: vote-pods
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/tuto-kube1/docker-images/vote
          name: vote-container
