apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
        - image: europe-west9-docker.pkg.dev/tuto-kube1/docker-images/worker
          name: woker-container
