- name: Set vm.vfs_cache_pressure to 90
  sysctl:
    name: vm.vfs_cache_pressure
    value: 90
    state: present
    sysctl_file: /etc/sysctl.conf
    reload: yes
  notify: Assert vm.vfs_cache_pressure value

- name: Verify vm.vfs_cache_pressure value
  command: sysctl vm.vfs_cache_pressure
  register: vfs_cache_pressure
