apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: db
  namespace: db-replica
  labels:
    kubernetes.io/service-name: db
addressType: IPv4
ports:
  - port: 5432
endpoints:
  - addresses:
      - "34.163.187.200"
